### ISSUE TITLE
undefined exception occurring when grunt is run

### ISSUE THREAD

**Issue by michaelezehi** [huei90/generator-mongoose-plugin#1]
Recently downloaded this generator and after installing and running npm install & bower install. Running grunt gives me this error. "Windows cannot find 'http://localhost:undefined'. Make sure you typed the name correctly and try again."
I have tried it on several machines with the same consequences. 

I have attached a screenshot of this error.

Any help with this would be greatly appreciated.

![mongoose-error-on-grunt-command](https://cloud.githubusercontent.com/assets/10596765/12289168/c332263a-b9d1-11e5-979f-e65202d4e426.png)

**Comment by hueitan** [comment]
I think this is not the problem of this generator.
You can try uninstall the grunt, grunt-cli, and try install grunt again.

**Comment by michaelezehi** [comment]
I have done that and the error still persists. My other projects that has grunt works perfectly. I have tried using the generator both at work and home, with the same result.

**Comment by hueitan** [comment]
Thanks for giving me more information.

In this plugin, there is not `grunt` file actually, why you are using grunt here.

**Comment by michaelezehi** [comment]
Hi, Just realised I posted to the wrong generator. I am using generator-mongoose. What does this plugin offer. It doesn't say in the description.

**Comment by hueitan** [comment]
The title "plugin" said it very clear :smile:

**Comment by michaelezehi** [comment]
Ha! thanks for that. Thanks for your swift response and really appreciate your help.

**Comment by hueitan** [comment]
yw
